config/routes.rb
Rails.application.routes.draw do

  resources :organizations
  devise_for :users
  resources :users
  get '/signup/:hash/:id' => 'users#signup', as: 'signup'

  namespace :admin do

    resources :organizations, except: [:show] do
      resources :agreements, only: [:create, :destroy]
    end
    resources :organization_members, only: [:create, :destroy]
    resources :notes,         only: [:create, :update, :destroy]
    resources :home_contents, only: [:index, :create, :update, :destroy]
    resources :attachments,   only: [:create, :destroy]
    resources :admins,        only: [:index, :create, :destroy]
    resources :supplies,      except: [:show]
    get 'supplies/list_form' => 'supplies#list_form', as: 'supplies_list_form'
    resources :users, except: [:show] do
      post 'mail',  as: 'mail', action: 'mail'
    end

    namespace :supply_lists do
      post  'add_owner/(:id)',     as: 'add_owner',     action: 'add_owner'
      post  'remove_owner/(:id)',  as: 'remove_owner',  action: 'remove_owner'
      get   'select',              as: 'select',        action: 'select'
      get   'download/:supply_id', as: 'download',      action: 'download'
    end
    resources :supply_lists, only: [:create, :destroy]



    namespace :imports do
      get  '/',             as: 'index',          action: 'index'
      post 'users',         as: 'users',          action: 'users'
      post 'organizations', as: 'organizations',  action: 'organizations'
      post 'supply_lists',  as: 'supply_lists',   action: 'supply_lists'
      get  'results/:key',  as: 'results',        action: 'results'
    end
    get   '/'                 => 'dashboard#index',   as: 'dashboard'
    post  '/dashboard/report' => 'dashboard#report',  as: 'dashboard_report'
  end

  root to: 'home#index'

  get '*path' => redirect('/')
end

app/controllers/admin/imports_controller.rb
class Admin::ImportsController < ApplicationController
  before_action :authenticate_admin

  def index
  end

  def users
    User.import(params[:user][:file], params[:user][:key])
    redirect_to admin_imports_index_path(key: params[:user][:key])
  end

  def organizations
    Organization.import(params[:organization][:file], params[:organization][:key])
    redirect_to admin_imports_index_path(key: params[:organization][:key])
  end

  def supply_lists
    SupplyList.import(params[:supply_list][:file], params[:supply_list][:key], params[:supply_list][:supply_id])
    redirect_to edit_admin_supply_path(params[:supply_list][:supply_id], key: params[:supply_list][:key], tab: 'load')
  end

  def results
    @log = UploadLog.find_by(key: params[:key])
    if @log
      render 'admin/imports/response', layout: false
    else
      render json: { error: 'Could not find the requested log.'}
    end
  end

end

app/views/admin/imports/index.html.haml
- cache set_keys([Attachment, UploadLog], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'imports'

    %div.col-md-10.col-xs-12.shad-left
      %h1 Imports

      %div.row
        %div.col-md-6.col-sm-6
          - cache set_keys([UploadLog], params) do
            %div.box
              %div.box-head
                %h4 Import Users
              %div#user.box-content
                - key1 = SecureRandom.hex
                = form_for :user, url: admin_imports_users_path, multipart: true do |f|
                  = f.hidden_field :key, value: key1
                  = f.file_field :file
                  %br
                  = f.submit 'Upload', class: 'btn btn-primary btn-sm', 'data-disable-with': 'uploading...'
                  %btn.btn.btn-default.btn-xs{ data: { toggle: 'modal', target: '#results' } } Results
            %div.box
              %div.box-head
                %h4 Import Organization
              %div#org.box-content
                - key2 = SecureRandom.hex
                = form_for :organization, url: admin_imports_organizations_path, multipart: true do |f|
                  = f.hidden_field :key, value: key2
                  = f.file_field :file
                  %br
                  = f.submit 'Upload', class: 'btn btn-primary btn-sm', 'data-disable-with': 'uploading...'
                  %btn.btn.btn-default.btn-xs{ data: { toggle: 'modal', target: '#results' } } Results
        %div.col-md-6.col-sm-6
          - cache do
            %div.box
              %div.box-head
                %h4 Downloads
              %div.box-content
                %ul.list-unstyled
                  %li
                    = link_to 'Download User Data', admin_users_path(format: :csv), class: 'btn btn-default btn-sm'
                  %li
                    = link_to 'Download Organization Data', admin_organizations_path(format: :csv), class: 'btn btn-default btn-sm'
                  %li
                    = link_to 'Download Supply Data', admin_supplies_path(format: :csv), class: 'btn btn-default btn-sm'
          - cache set_keys([Attachment]) do
            %div.box
              %div.box-head
                %h4 Attachments
              %div.box-content
                %table.table
                  %thead
                    %tr
                      %th Name
                      %th Delete
                  - Attachment.all.each do |attachment|
                    %tr
                      %td
                        = link_to attachment.filename, attachment.file.url, target: '_blank'
                      %td
                        = link_to 'Delete', admin_attachment_path(attachment), method: :delete
              %div.box-foot
                = form_tag admin_attachments_path, method: :post, multipart: true do
                  = file_field_tag :file, class: 'short-form'
                  = submit_tag 'Add', class: 'btn-link'

  = render 'admin/shared/results'

app/views/admin/imports/response.html.haml
%h3
  Results From
  = @log.log['info']['name']
  Upload

%h4 Summary
%table.table
  %thead
    %tr
      %th Name
      %th Total
  %tr
    %td
      New
    %td
      = @log.log['info']['total_new']
  %tr
    %td
      Updated
    %td
      = @log.log['info']['total_updated']
  %tr
    %td
      Errors
    %td
      = @log.log['info']['total_errors']
  %tfoot
    %tr.active
      %td
        Total
      %td
        = @log.log['info']['total_records']

%h4 New Records
=raw @log.log['successes']['new'].to_table

%h4 Updated Records
=raw @log.log['successes']['updated'].to_table

%h4 Errors
=raw @log.log['errors'].to_table