config/routes.rb
Rails.application.routes.draw do

  resources :organizations
  devise_for :users
  resources :users
  get '/signup/:hash/:id' => 'users#signup', as: 'signup'

  namespace :admin do

    resources :organizations, except: [:show] do
      resources :agreements, only: [:create, :destroy]
    end
    resources :organization_members, only: [:create, :destroy]
    resources :notes,         only: [:create, :update, :destroy]
    resources :home_contents, only: [:index, :create, :update, :destroy]
    resources :attachments,   only: [:create, :destroy]
    resources :admins,        only: [:index, :create, :destroy]
    resources :supplies,      except: [:show]
    get 'supplies/list_form' => 'supplies#list_form', as: 'supplies_list_form'
    resources :users, except: [:show] do
      post 'mail',  as: 'mail', action: 'mail'
    end

    namespace :supply_lists do
      post  'add_owner/(:id)',     as: 'add_owner',     action: 'add_owner'
      post  'remove_owner/(:id)',  as: 'remove_owner',  action: 'remove_owner'
      get   'select',              as: 'select',        action: 'select'
      get   'download/:supply_id', as: 'download',      action: 'download'
    end
    resources :supply_lists, only: [:create, :destroy]



    namespace :imports do
      get  '/',             as: 'index',          action: 'index'
      post 'users',         as: 'users',          action: 'users'
      post 'organizations', as: 'organizations',  action: 'organizations'
      post 'supply_lists',  as: 'supply_lists',   action: 'supply_lists'
      get  'results/:key',  as: 'results',        action: 'results'
    end
    get   '/'                 => 'dashboard#index',   as: 'dashboard'
    post  '/dashboard/report' => 'dashboard#report',  as: 'dashboard_report'
  end

  root to: 'home#index'

  get '*path' => redirect('/')
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  paginates_per 24
  SECTORS = %w[Sector1 Sector2]

  include Validators
  include Tagging::Instance
  extend  Tagging::ClassMethods

  has_many :organization_members, dependent: :destroy
  has_many :supply_lists,         dependent: :destroy
  has_many :users,                through: :organization_members
  has_many :agreements,           dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates_with InactiveOnValidator

  def self.all_active
    where(current: true)
  end

  def description_short
    self.description.slice(0,10) if description
  end

  def agreement
    self.signed_service_agreement ? '√' : 'X' # todo change this to look at currently valid?
  end

  def active
    self.current ? '√' : 'X'
  end

  scope :search,  -> (s) { q = "%#{s}%" ; where('name ILIKE ? OR description ILIKE ? OR tags @> ARRAY[?] OR city ILIKE ? OR province ILIKE ? OR postal ILIKE ?', q, q, ["#{s}"], q, q, q) }
  scope :current, -> (s) { s == 'Active' ? q = true : q = false ; where(current: q) if s }

  def self.import(csv, key)
    self.import_base(
      csv, key: key, merge: {},
      slice: %w(name description signed_service_agreement current inactive_on address city province postal)
    )
  end

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_action :authenticate_admin

  def index
    @organizations = Organization.all.order(:name).includes(:organization_members).page(params[:page]).per(per_page(params[:per_page]))
    filter_params(params).each do |search, result|
      @organizations = @organizations.public_send(search, result) if result.present?
    end
    respond_to { |format| format.html ; format.csv { send_data(Organization.build_csv) }  }
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      flash[:success] = 'Organization created!'
      redirect_to edit_admin_organization_path(@organization)
    else
      flash[:danger] = "Organization create failed. #{@organization.errors.full_messages.to_sentence}"
      redirect_to new_admin_organization_path
    end
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def update
    @organization = Organization.find(params[:id])
    if @organization.update(organization_params)
      flash[:success] = 'Organization edited!'
      redirect_to edit_admin_organization_path(@organization)
    else
      flash[:danger] = "Organization update failed. #{@organization.errors.full_messages.to_sentence}"
      redirect_to edit_admin_organization_path(@organization)
    end
  end

  def destroy
    Organization.find(params[:id]).destroy
    flash[:success] = 'Organization deleted.'
    redirect_to admin_organizations_path
  end

  private
    def organization_params
      params.require(:organization).permit(
        :name, :description, :avatar, :signed_service_agreement,
        :current, :inactive_on, :address, :city, :province, :postal, :tags, :tagging
      )
    end

    def filter_params(params)
      params.slice(:search, :current)
    end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :index, :update, :destroy]

  def index
    @organizations = Organization.all_active.order(:name).page(params[:page]).per(per_page(params[:per_page], 24)).includes(:organization_members)
    filter_params(params).each do |search, result|
      @organizations = @organizations.public_send(search, result) if result.present?
    end
  end

  def edit
    organization = Organization.find(params[:id])
    if editable?(organization)
      @organization = organization
    else
      flash[:danger] = 'You do not have the permissions'
      redirect_to root_path
    end
  end

  def update
    @organization = Organization.find(params[:id])
    if editable?(@organization)
      if @organization.update(organization_params)
        flash[:success] = 'Organization edited!'
        redirect_to organizations_path
      else
        flash[:danger] = "Organization update failed. #{@organization.errors.full_messages.to_sentence}"
        render 'edit'
      end
    else
      flash[:danger] = 'You do not have the permissions'
      redirect_to root_path
    end
  end

  def destroy
    organization = Organization.find(params[:id])
    if editable?(organization)
      organization.destroy
      flash[:success] = 'Organization deleted.'
      redirect_to root_path
    else
      flash[:danger] = 'You do not have the permissions'
      redirect_to root_path
    end
  end

  private
  def organization_params
    params.require(:organization).permit(:avatar, :name, :sector, :twitter, :tagging, :description)
  end

  def filter_params(params)
    params.slice(:search, :current)
  end


end

app/views/admin/organizations/_form.html.haml
%div.box
  %div.box-head
    %h4
      = org.name ? org.name : 'New'
  %div.box-content
    = form_for org, url: url, method: method do |f|
      %div.form-group
        %label Name
        = f.text_field :name, placeholder: 'organization name', class: 'form-control'
      %div.form-group
        %label Tags (comma separated)
        %br
        = f.text_field :tagging, value: org.tags.join(','), class: 'form-control', id: 'tagsinput'
        %div.form-group
          %label Sector
          = f.select :sector, Organization::SECTORS.collect { |s| [s,s] }, {include_blank: '', }, {class: 'form-control'}
        %div.form-group
          %label Twitter
          %div.input-group
            %div.input-group-addon @
            = f.text_field :twitter, placeholder: 'my-twitter-handle', class: 'form-control'
      %div.form-group
        %label
          Avatar
          = link_to 'view current avatar', org.avatar.url, target: '_blank' if org.avatar.present?
        = f.file_field :avatar
        %br
        = f.label 'Currently Active: '
        = f.check_box :current, id: 'current'
        %div#currentShow{ style: org.current ? 'display:none' : '' }
          %label Inactive on:&nbsp;
          = f.date_field :inactive_on, include_blank: true
        %br
        = f.label 'Signed Agreement: '
        = f.check_box :signed_service_agreement
      %div.form-group
        %label Address
        = f.text_field :address, placeholder: 'address', class: 'form-control'
        %div{ style: 'width:100%' }
          = f.text_field :city, placeholder: 'city', class: 'form-control short-form', style: 'width:45%'
          = f.text_field :province, placeholder: 'prov.', class: 'form-control short-form', style: 'width:22%'
          = f.text_field :postal, placeholder: 'postal', class: 'form-control short-form', style: 'width:33%'
        %br
        %br
      %div.form-group
        %label Description
        = f.text_area :description, placeholder: 'description', class: 'form-control', rows: 3
      = f.submit 'Submit', class: 'btn btn-primary', data: { disable_with: 'processing...' }
:javascript
  $('#current').click(function() {
      if( $(this).is(':checked')) {
          $("#currentShow").hide();
      } else {
          $("#currentShow").show();
      }
  });

app/views/admin/organizations/_list.html.haml
- cache set_keys([User, org]) do
  %div.box
    %div.box-head
      %h4 Users
    %div.box-content
      %table.table
        %thead
          %tr
            %th User Name
            %th User Email
            %th Administrator
            %th Accountant
            %th Actions
        - org.organization_members.includes(:user).each do |member|
          %tr
            %td
              = link_to member.user.name, edit_admin_user_path(member.user)
            %td
              = member.user.email
            %td
              = member.admin_contact
            %td
              = member.account_contact
            %td
              = link_to 'remove', admin_organization_member_path(member), method: :delete
    %div.box-foot
      = form_for :organization_member, url: admin_organization_members_path, method: :post do |f|
        = f.select :user_id, options_from_collection_for_select(User.all.order(:name), :id, :name), {}, {class: 'short-form form-control'}
        = f.hidden_field :organization_id, value: params[:id]
        &nbsp;&nbsp;
        = f.check_box :account_contact
        = f.label 'Accountant?'
        &nbsp;&nbsp;
        = f.check_box :admin_contact
        = f.label 'Administrator?'
        &nbsp;
        = f.submit 'Add User', class: 'btn btn-primary', 'data-disable-with': 'processing...'
- cache set_keys([org], name: 'org-sup') do
  %div.box
    %div.box-head
      %h4 Organization Wide Supplies
    %div.box-content
      %table.table
        %thead
          %tr
            %th Supply Name
            %th Name
            %th Notes
            %th Action
        - org.supply_lists.each do |list|
          %tr
            %td
              = link_to list.supply.name, edit_admin_supply_path(list.supply)
            %td
              = list.name
            %td
              = list.notes
            %td
              = link_to 'remove', admin_supply_lists_remove_owner_path(list), method: :post
    %div.box-foot
      = form_tag admin_supply_lists_add_owner_path, method: :post do
        = render 'admin/shared/sup_sel'
        = hidden_field_tag :organization_id, org.id
        = text_field_tag :notes, '', placeholder: 'notes', class: 'form-control short-form'
        = submit_tag 'Add', class: 'btn btn-primary', 'data-disable-with': 'processing...'
- cache set_keys([org], name: 'sas') do
  %div.box
    %div.box-head
      %h4 Service Agreements
    %div.box-content
      %table.table
        %thead
          %tr
            %th File Name
            %th Valid Until
            %th Created At
            %th Actions
        - org.agreements.each do |item|
          %tr
            %td
              - name = item.name.present? ? item.name : item.agreement.filename
              = link_to name, item.agreement.url
            %td
              = day item.valid_until
            %td
              = day item.created_at
            %td
              = link_to 'delete', admin_organization_agreement_path(org, item), method: :delete
    %div.box-foot
      = form_for :agreement, url: admin_organization_agreements_path(org), method: :post do |f|
        = f.text_field :name, placeholder: 'name', class: 'form-control short-form'
        = f.date_field :valid_until, class: 'form-control short-form'
        = f.file_field :agreement, class: 'short-form form-control'
        = f.submit 'Add Agreement', class: 'btn btn-primary', 'data-disable-with': 'processing...'

app/views/admin/organizations/edit.html.haml
- cache [set_keys([@organization, User]), 'edit'] do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Organizations'
    %div.col-md-10.shad-left
      %h1 Organizations
      %ul.nav.nav-tabs
        %li{ role: 'presentation' }
          = link_to 'Organizations', admin_organizations_path
        %li{ role: 'presentation' }
          = link_to 'New', new_admin_organization_path
        %li.active{ role: 'presentation' }
          = link_to @organization.name, '#'

      %br
      %div.col-md-4
        - cache [set_keys([@organization]), 'form edit'] do
          = render 'admin/organizations/form', org: @organization, url: admin_organization_path(@organization), method: :put
      %div.col-md-8
        - cache [set_keys([@organization, User]), 'list'] do
          = render 'list', org: @organization

app/views/admin/organizations/index.html.haml
- cache set_keys([Organization], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Organizations'
    %div.col-md-10.col-xs-12.shad-left
      %h1 Organizations

      %ul.nav.nav-tabs
        %li.active{ role: 'presentation' }
          = link_to 'Organizations', admin_organizations_path
        %li{ role: 'presentation' }
          = link_to 'New Organization', new_admin_organization_path
      %br
      %div.search
        %div.col-md-4
          = render '/admin/shared/search_active'
        = render 'shared/pagination_top', object: @organizations

        %p{ style: 'text-align:right' }

      = render 'admin/shared/table', model: Organization, data: @organizations,
          header: %w"Name Active Agreement Employees Tags Actions",
          methods: [['Link', :name, :edit_admin_organization_path], :active, :agreement, ['Double', :organization_members,:size], :pretty_tags],
          links: [ ['edit', :edit_admin_organization_path], ['delete', :admin_organization_path, method: :delete, data: { confirm: 'This will delete the record in the database permanently.' } ] ]

      %div.text-center
        = paginate @organizations, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-centered'
        %br
        = page_entries_info @organizations
        %br
        %span Results:
        = link_to '10', params.merge(per_page: 10)
        = link_to '20', params.merge(per_page: 20)
        = link_to '50', params.merge(per_page: 50)
        = link_to '100', params.merge(per_page: 100)
        = link_to '200', params.merge(per_page: 200)

app/views/admin/organizations/new.html.haml
- cache do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Organizations'
    %div.col-md-10.shad-left
      %h1 Organizations
      %ul.nav.nav-tabs
        %li{ role: 'presentation' }
          = link_to 'Organizations', admin_organizations_path
        %li.active{ role: 'presentation' }
          = link_to 'New Organization', new_admin_organization_path

      %br
      %div.col-md-4
        = render 'admin/organizations/form', url: admin_organizations_path, method: :post, org: @organization