config/routes.rb
Rails.application.routes.draw do

  resources :organizations
  devise_for :users
  resources :users
  get '/signup/:hash/:id' => 'users#signup', as: 'signup'

  namespace :admin do

    resources :organizations, except: [:show] do
      resources :agreements, only: [:create, :destroy]
    end
    resources :organization_members, only: [:create, :destroy]
    resources :notes,         only: [:create, :update, :destroy]
    resources :home_contents, only: [:index, :create, :update, :destroy]
    resources :attachments,   only: [:create, :destroy]
    resources :admins,        only: [:index, :create, :destroy]
    resources :supplies,      except: [:show]
    get 'supplies/list_form' => 'supplies#list_form', as: 'supplies_list_form'
    resources :users, except: [:show] do
      post 'mail',  as: 'mail', action: 'mail'
    end

    namespace :supply_lists do
      post  'add_owner/(:id)',     as: 'add_owner',     action: 'add_owner'
      post  'remove_owner/(:id)',  as: 'remove_owner',  action: 'remove_owner'
      get   'select',              as: 'select',        action: 'select'
      get   'download/:supply_id', as: 'download',      action: 'download'
    end
    resources :supply_lists, only: [:create, :destroy]



    namespace :imports do
      get  '/',             as: 'index',          action: 'index'
      post 'users',         as: 'users',          action: 'users'
      post 'organizations', as: 'organizations',  action: 'organizations'
      post 'supply_lists',  as: 'supply_lists',   action: 'supply_lists'
      get  'results/:key',  as: 'results',        action: 'results'
    end
    get   '/'                 => 'dashboard#index',   as: 'dashboard'
    post  '/dashboard/report' => 'dashboard#report',  as: 'dashboard_report'
  end

  root to: 'home#index'

  get '*path' => redirect('/')
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  has_many :supply_lists, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def picks
    supply_lists.where('organization_id IS NULL OR user_id IS NULL').order(:name)
  end

  def in_use
    self.supply_lists.where('organization_id IS NOT NULL OR user_id IS NOT NULL').count
  end

  scope :search, -> (s) { q = "%#{s}%" ; where('name ILIKE ? OR notes ILIKE ?', q, q) }

end

app/controllers/admin/supplies_controller.rb
class Admin::SuppliesController < ApplicationController
  before_action :authenticate_admin

  def index
    @supplies = Supply.all.includes(:supply_lists).page(params[:page]).per(per_page(params[:per_page]))
    @supplies = @supplies.search(params[:search]) if params[:search]
    respond_to { |format| format.html ; format.csv { send_data(SupplyList.build_csv) }  }
  end

  def new
    @supply = Supply.new
  end

  def create
    @supply = Supply.new(supply_params)
    if @supply.save
      flash[:success] = "Supply #{@supply.name} successfully created."
      redirect_to :back
    else
      flash[:danger] = "Failed to create. #{@supply.errors.full_messages.to_sentence}"
      redirect_to :back
    end
  end

  def edit
    @supply = Supply.find(params[:id])
    @supply_lists = @supply.supply_lists.includes([:user, :organization]).order(:name).page(params[:page]).per(per_page(params[:per_page]))
    filter_params(params).each do |search, result|
      @supply_lists = @supply_lists.order(:name).public_send(search, result) if result.present?
    end
  end

  def list_form
    render layout: false
  end

  def update
    @supply = Supply.find(params[:id])
    if @supply.update(supply_params)
      flash[:success] = "Supply #{@supply.name} updated!"
      redirect_to :back
    else
      flash[:danger] = "Supply update failed: #{@supply.errors.full_messages.to_sentence}"
      redirect_to :back
    end
  end

  def destroy
    Supply.find(params[:id]).destroy
    flash[:success] = 'supply deleted.'
    redirect_to admin_supplies_path
  end

  private
    def supply_params
      params.require(:supply).permit(
        :name, :notes,
        supply_lists_attributes: [:name, :notes, :organization_id, :user_id, :id, :_destroy]
      )
    end

    def filter_params(params)
      params.slice(:category, :search)
    end

end

app/views/admin/supplies/_form.html.haml
%div.box
  %div.box-head
    %h4
      = supply.name ? supply.name : 'New'
  %div.box-content
    = form_for supply, url: url, method: method do |f|
      %div.form-group
        %label Name
        = f.text_field :name, placeholder: 'name', class: 'form-control'
      %div.form-group
        %label Description
        = f.text_area :notes, placeholder: 'notes', class: 'form-control'
      %br
      = f.submit 'Submit', class: 'btn btn-primary'
      %br
      %br
      %div
        %table.table
          %tr
            %td
              In Use:
            %td
              = supply.in_use
          %tr
            %td
              Available:
            %td
              = supply.supply_lists.count - supply.in_use
          %tr
            %td
              Total:
            %td
              = supply.supply_lists.count

app/views/admin/supplies/_list.html.haml
%ul.nav.nav-tabs{ role: 'tablist' }
  %li{ role: 'presentation', class: (params[:tab] == 'search' or params[:tab].nil? or params[:tab] == '') ? 'active' : '' }
    %a{ href: '#search', 'aria-controls' => 'search', role: 'tab', 'data-toggle' => 'tab' } View
  %li{ role: 'presentation', class: params[:tab] == 'add' ? 'active' : '' }
    %a{ href: '#add', 'aria-controls' => 'add', role: 'tab', 'data-toggle' => 'tab' } New
  %li{ role: 'presentation', class: params[:tab] == 'load' ? 'active' : '' }
    %a{ href: '#load', 'aria-controls' => 'load', role: 'tab', 'data-toggle' => 'tab' } Upload/Download

%div.tab-content.box{ style: 'margin:0 0 0 0; border-top: none;' }
  %div.tab-pane.box-content#search{ role: 'tabpanel', class: (params[:tab] == 'search' or params[:tab].nil? or params[:tab] == '') ? 'active' : '' }
    %br
    %div.col-md-7
      = form_tag '#', method: :get, enforce_utf8: false do
        = text_field_tag :search, params[:search], placeholder: 'search', class: 'form-control short-form'
        = hidden_field_tag :tab, params[:tab]
        = select_tag :category, options_for_select(%W"User Organization Unused", params[:category] ), include_blank: 'Type?', class: 'form-control short-form', style: 'width:100px;'
        = submit_tag 'Search', name: nil, class: 'btn btn-default short-form', data: { disable_with: 'searching...' }
    %div.col-md-5
      %small
        = page_entries_info @supply_lists
      %br
      Results:
      = link_to '10', params.merge(per_page: 10)
      = link_to '20', params.merge(per_page: 20)
      = link_to '50', params.merge(per_page: 50)
      = link_to '100', params.merge(per_page: 100)
      = link_to '200', params.merge(per_page: 200)
      = link_to 'all', params.merge(per_page: 5000)
    %div.row
      %div.text-center{ style: 'padding:10px 0 10px 0' }
        = paginate @supply_lists

    %div
      %table.table
        %thead
          %tr
            %th Name
            %th Owner Type
            %th Owner Name
            %th Notes
            %th Actions
        - @supply_lists.order(:name).each do |list|
          %tr
            %td
              = list.name
            %td
              = list.type
            %td
              = list.owner.name if list.owner
            %td
              = list.notes
            %td
              = link_to 'delete', admin_supply_list_path(list), method: :delete
              = link_to 'remove', admin_supply_lists_remove_owner_path(list), method: :post
              %button.btn-link{ style: 'padding:0;', id: "pop#{list.id}", title: "Add Owner to #{list.name} <button class='close' onclick=$('#pop#{list.id}').popover('hide')>&times;</button>", data: { toggle: 'popover', placement: 'left' } } add
              %div.popover-content{ style: 'padding:0;' }
                %div.hidden{ id: "form#{list.id}", style: 'height:0;' }
                  = form_tag admin_supply_lists_add_owner_path, method: :post do
                    = hidden_field_tag :id, list.id
                    %div.addForm
                :javascript
                  $("#pop#{list.id}").popover({
                    html: true,
                    content: function () {
                      return $("#form#{list.id}").html();
                    }
                  });
      = render 'shared/pagination_bottom', object: @supply_lists

  %div.tab-pane.box-content#add{ role: 'tabpanel', class: params[:tab] == 'add' ? 'active' : '' }
    %br
    %h4 Create New Supply Item
    = form_for :supply_list, url: admin_supply_lists_path, method: :post do |f|
      = f.text_field :name, placeholder: 'name', class: 'form-control short-form'
      = f.hidden_field :supply_id, value: supply.id
      = f.text_field :notes, placeholder: 'notes', class: 'form-control short-form'
      = f.submit 'Submit', class: 'btn btn-primary', data: { disable_with: 'processing...' }

  %div.tab-pane.box-content#load{ role: 'tabpanel', class: params[:tab] == 'load' ? 'active' : '' }
    %br
    %div
      %h4
        = link_to 'Download', admin_supply_lists_download_path(supply, format: :csv)
      %br
      %h4 Upload Csv
      %p Make sure that your column heading on your spreadsheet (the first row), match the following (id,name,notes). Try downloading by clicking above to see what it should look like. If you download a file and re-upload it, changed records will be updated as long as the ID remains. Don't put an ID for new records. Only ID and name are required.
      %div#upload
        - key = SecureRandom.hex
        = form_for :supply_list, url: admin_imports_supply_lists_path, multipart: true do |f|
          = f.hidden_field :supply_id, value: supply.id
          = f.hidden_field :key, value: key
          = f.file_field :file
          %br
          = f.submit 'Upload', class: 'btn btn-primary btn-sm', 'data-disable-with': 'uploading...'
          %btn.btn.btn-default.btn-xs{ data: { toggle: 'modal', target: '#results' } } Results

= render 'admin/shared/results'

app/views/admin/supplies/_tabs.html.haml
%ul.nav.nav-tabs
  %li{ role: 'presentation', class: all }
    = link_to 'All', admin_supplies_path
  %li{ role: 'presentation', class: new }
    = link_to 'New', new_admin_supply_path
  - Supply.all.each do |supply|
    - cur = @supply ? @supply.id : nil
    %li{ role: 'presentation', class: supply.id == cur ? 'active' : '' }
      = link_to truncate(supply.name, length: 10), edit_admin_supply_path(supply)

app/views/admin/supplies/edit.html.haml
- cache set_keys([Supply, @supply], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Supplies'
    %div.col-md-10.shad-left
      %h1 Supplies
      - cache set_keys([Supply], params) do
        = render 'admin/supplies/tabs', all: '', new: ''

      %br
      %div.row
        %div.col-md-3
          - cache set_keys([@supply]) do
            = render 'admin/supplies/form', supply:  @supply, url: admin_supply_path(@supply), method: :put
        %div.col-md-9
          - cache [set_keys([@supply], params), 'list'] do
            = render '/admin/supplies/list', supply: @supply, url: admin_supply_path(@supply), method: :put
:javascript
  $.ajax({
    url:      "/admin/supplies/list_form.html",
    method:   'get',
    dataType: "html",
    success: function (data) {
      $(".addForm").each( function(i,obj) {
        $(obj).html(data)
      })
    }
  });

app/views/admin/supplies/index.html.haml
- cache set_keys([Supply], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Supplies'
    %div.col-md-10.col-xs-12.shad-left
      %h1 Supplies
      - cache [set_keys([Supply], params), 'tabs'] do
        = render 'admin/supplies/tabs', all: '', new: ''
      %br
      %div.col-md-4
        = form_tag '#', method: :get, enforce_utf8: false do
          = text_field_tag :search, params[:search], placeholder: 'search', class: 'form-control short-form'
          = hidden_field_tag :tab, params[:tab]
          = select_tag :category, options_for_select(%W"User Organization Unused", params[:category] ), include_blank: 'Type?', class: 'form-control short-form', style: 'width:100px;'
          = submit_tag 'Search', name: nil, class: 'btn btn-default short-form', data: { disable_with: 'searching...' }
      = render 'shared/pagination_top', object: @supplies

      = render 'admin/shared/table', model: Supply, data: @supplies, header: %w"Name Total In-Use Notes Actions", methods: [['Link', :name, :edit_admin_supply_path], ['Double', :supply_lists, :size], :in_use, :notes], links: [ ['edit', :edit_admin_supply_path], ['delete', :admin_supply_path, method: :delete, data: { confirm: 'This will delete the record in the database permanently.' }] ]

      %div.text-center
        = paginate @supplies, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-centered'
        %br
        = page_entries_info @supplies
        %br
        %span Results:
        = link_to '10', params.merge(per_page: 10)
        = link_to '20', params.merge(per_page: 20)
        = link_to '50', params.merge(per_page: 50)
        = link_to '100', params.merge(per_page: 100)
        = link_to '200', params.merge(per_page: 200)

app/views/admin/supplies/list_form.html.haml
- cache set_keys([Organization, User], params) do
  = select_tag :organization_id, options_from_collection_for_select(Organization.all.order(:name), :id, :name), {include_blank: 'Add Organization',  class: 'form-control' }
  = select_tag :user_id, options_from_collection_for_select(User.all.order(:name), :id, :name), {include_blank: 'Add User',  class: 'form-control' }
  = submit_tag 'add', class: 'btn btn-primary'

app/views/admin/supplies/new.html.haml
- cache set_keys([Supply], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Supplies'
    %div.col-md-10.shad-left
      %h1 Supplies
      - cache set_keys([Supply], params) do
        = render 'admin/supplies/tabs', all: '', new: ''

      %div.row
        %div.col-md-3
          = render 'admin/supplies/form', supply: @supply, url: admin_supplies_path, method: :post