config/routes.rb
Rails.application.routes.draw do

  resources :organizations
  devise_for :users
  resources :users
  get '/signup/:hash/:id' => 'users#signup', as: 'signup'

  namespace :admin do

    resources :organizations, except: [:show] do
      resources :agreements, only: [:create, :destroy]
    end
    resources :organization_members, only: [:create, :destroy]
    resources :notes,         only: [:create, :update, :destroy]
    resources :home_contents, only: [:index, :create, :update, :destroy]
    resources :attachments,   only: [:create, :destroy]
    resources :admins,        only: [:index, :create, :destroy]
    resources :supplies,      except: [:show]
    get 'supplies/list_form' => 'supplies#list_form', as: 'supplies_list_form'
    resources :users, except: [:show] do
      post 'mail',  as: 'mail', action: 'mail'
    end

    namespace :supply_lists do
      post  'add_owner/(:id)',     as: 'add_owner',     action: 'add_owner'
      post  'remove_owner/(:id)',  as: 'remove_owner',  action: 'remove_owner'
      get   'select',              as: 'select',        action: 'select'
      get   'download/:supply_id', as: 'download',      action: 'download'
    end
    resources :supply_lists, only: [:create, :destroy]



    namespace :imports do
      get  '/',             as: 'index',          action: 'index'
      post 'users',         as: 'users',          action: 'users'
      post 'organizations', as: 'organizations',  action: 'organizations'
      post 'supply_lists',  as: 'supply_lists',   action: 'supply_lists'
      get  'results/:key',  as: 'results',        action: 'results'
    end
    get   '/'                 => 'dashboard#index',   as: 'dashboard'
    post  '/dashboard/report' => 'dashboard#report',  as: 'dashboard_report'
  end

  root to: 'home#index'

  get '*path' => redirect('/')
end

app/models/user.rb
class User < ActiveRecord::Base
  include Validators
  has_many :admins, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many  :supply_lists,          dependent:  :nullify
  has_many  :supplies,              through:    :supply_lists
  has_many  :organization_members,  dependent:  :destroy
  has_many  :organizations,         through:    :organization_members
  has_one   :admin,                 dependent:  :destroy

  mount_uploader :avatar, AvatarUploader

  paginates_per 24

  validates_with InactiveOnValidator

  def self.all_active
    all.where(current: true)
  end

  def active
    self.current ? '√' : 'X'
  end

  def desk
    desk = self.supply_lists.find_all { |list| ::DESK_ID.include?(list.supply_id) }
    desk.first.name if desk.first
  end

  def organization_supplies
    ids = self.organizations.pluck(:id)
    SupplyList.where(organization_id: ids)
  end

  def all_supplies
    organization_supplies + supply_lists
  end

  def verify_signup_digest?(digest)
    if self.signup_digest == digest
      self.update(signup_digest: nil)
    else
      false
    end
  end

  def send_mail(content)
    digest = SecureRandom.urlsafe_base64
    update(signup_digest: digest)
    UserMailer.new_user(self, digest, content).deliver_now
  end

  scope :search,  -> (s) { q = "%#{s}%" ; where('name ILIKE ? OR email ILIKE ? OR phone ILIKE ? OR account_type ILIKE ?', q, q, q, q) }
  scope :current, -> (s) { s == 'Active' ? q = true : q = false ; where(current: q) if s }

  def self.import(csv, key)
    self.import_base(
      csv, key: key, password: true, merge: {},
      slice: %w(name email phone account_type inactive_on current password password_confirmation)
    )
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin

  def index
    @users = User.order(:name).page(params[:page]).per(per_page(params[:per_page])).includes(:supply_lists)
    filter_params(params).each do |search, result|
      @users = @users.public_send(search, result) if result.present?
    end
    respond_to { |format| format.html ; format.csv { send_data(User.build_csv) }  }
  end

  def new
    @user = User.new
  end

  def mail
    user = User.find(params[:user_id])
    user.send_mail(params[:mail])
    flash[:success] = "Email sent to #{user.name}."
    redirect_to :back
  end

  def create
    pass = SecureRandom.hex(10)
    @user = User.new( user_params.merge(password: pass, password_confirmation: pass) )
    if @user.save
      flash[:success] = 'User created!'
      redirect_to edit_admin_user_path(@user)
    else
      flash.now[:danger] = "User create failed. #{@user.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    clear_password(params[:user][:password], params[:user][:password_confirmation])
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'User edited!'
      redirect_to edit_admin_user_path(@user)
    else
      flash[:danger] = "User update failed. #{@user.errors.full_messages.to_sentence}"
      redirect_to edit_admin_user_path(@user)
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted.'
    redirect_to :back
  end

  private
    def user_params
      params.require(:user).permit(
        :name, :email, :phone, :account_type, :inactive_on, :current,
        :password, :password_confirmation, :tags, :tagging, :notes,
        :linked_in
      )
    end

    def filter_params(params)
      params.slice(:search, :current)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,  only: [:edit, :update, :index]
  before_action :correct_user,        only: [:edit, :update]

  def index
    @users = User.all_active.order(:name).page(params[:page]).per(per_page(params[:per_page], 24))
  end

  def signup
    @user = User.find_by(id: params[:id])
    if @user && @user.verify_signup_digest?(params[:hash])
      sign_out_all_scopes
      sign_in :user, @user
      flash[:success] = 'Successfully signed up. Please create a new password.'
      redirect_to edit_user_path(@user)
    else
      flash[:danger] = 'We are experiencing an error, please contact support.'
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    clear_password(params[:user][:password], params[:user][:password_confirmation])
    @user = User.find(params[:id])
    if @user.update(user_params)
      sign_in(@user, bypass: true)
      flash[:success] = 'Account updated.'
      redirect_to edit_user_path(@user)
    else
      flash[:danger] = "User update failed. #{@user.errors.full_messages.to_sentence}"
      redirect_to edit_user_path(@user)
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :name, :email, :phone, :password, :password_confirmation,
        :linked_in, :avatar
      )
    end

    def correct_user
      unless params[:id].to_i == current_user.id
        flash[:danger] = 'You do not have the permissions'
        redirect_to root_path
      end
    end

end

app/views/admin/users/_form.html.haml
%div.box
  %div.box-head
    %h4
      = user.name ? user.name : 'New'
  %div.box-content
    = form_for user, url: url, method: method do |f|
      %div.form-group
        %label Name
        = f.text_field :name, class: 'form-control'
      %div.form-group
        %label Email
        = f.email_field :email, class: 'form-control'
      %div.form-group
        %label
          Avatar
          = link_to 'view current avatar', user.avatar.url, target: '_blank' if user.avatar.present?
        = f.file_field :avatar
      %div.form-group
        %label Phone
        = f.phone_field :phone, class: 'form-control'
      %div.form-group
        %label Account Type
        = f.phone_field :account_type, class: 'form-control'
      %div.form-group
        %label
          = link_to 'LinkedIn', user.linked_in
        = f.text_field :linked_in, class: 'form-control'
      = f.label 'Currently Active: '
      = f.check_box :current, id: 'current'
      %div#currentShow{ style: user.current ? 'display:none' : '' }
        = f.label 'Inactive on:'
        = f.date_select :inactive_on, include_blank: true
      %br
      %br
      = f.submit 'Submit', class: 'btn btn-primary', data: { disable_with: 'processing...' }
    %br
    %span User is an administrator?
    = user.admin ? 'Yes' : 'No'

:javascript
  $('#current').click(function() {
    if( $(this).is(':checked')) {
      $("#currentShow").hide();
    } else {
      $("#currentShow").show();
    }
  });

app/views/admin/users/_list.html.haml
- cache set_keys([user, Supply]) do
  %div.box
    %div.box-head
      %h4 Supplies
    %div.box-content
      %table.table
        %thead
          %tr
            %th Supply Name
            %th Name
            %th Notes
            %th Organization
            %th Action
        - user.supply_lists.each do |list|
          - cache(list) do
            %tr
              %td
                = link_to list.supply.name, edit_admin_supply_path(list.supply)
              %td
                = list.name
              %td
                = list.notes
              %td -
              %td
                = link_to 'remove', admin_supply_lists_remove_owner_path(list), method: :post
        - user.organization_supplies.each do |list|
          - cache(list) do
            %tr
              %td
                = link_to list.supply.name, edit_admin_supply_path(list.supply)
              %td
                = list.name
              %td
                = list.notes
              %td
                = list.organization.name
              %td -
    %div.box-foot
      %div
        = form_tag admin_supply_lists_add_owner_path, method: :post, id: 'supSelect' do
          = render 'admin/shared/sup_sel'
          = hidden_field_tag :user_id, user.id
          = text_field_tag :notes, '', placeholder: 'notes', class: 'form-control short-form'
          = submit_tag 'Add', class: 'btn btn-primary'
- cache set_keys([user, user.organization_members, Organization]) do
  %div.box
    %div.box-head
      %h4 Organizations
    %div.box-content
      %table.table
        %thead
          %tr
            %th Organization Name
            %th Admin Contact
            %th Accountant
            %th Remove
        - user.organization_members.each do |list|
          - cache(list) do
            %tr
              %td
                = link_to list.organization.name, edit_admin_organization_path(list.organization)
              %td
                = list.admin_contact
              %td
                = list.account_contact
              %td
                = link_to 'remove', admin_organization_member_path(list), method: :delete
    %div.box-foot
      = form_for :organization_member, url: admin_organization_members_path, method: :post do |f|
        = f.hidden_field :user_id, value: user.id
        = f.select :organization_id, options_from_collection_for_select(Organization.all, :id, :name), {}, {class: ' short-form form-control'}
        &nbsp;&nbsp;
        = f.check_box :account_contact
        = f.label 'Accountant?'
        &nbsp;&nbsp;
        = f.check_box :admin_contact
        = f.label 'Administrator?'
        &nbsp;&nbsp;
        = f.submit 'Add', class: 'btn btn-primary'
- cache set_keys([user, Attachment]) do
  %div.box
    %div.box-head
      %h4 Send Email
    %div.box-content
      = form_tag admin_user_mail_path(user), method: :post do
        = fields_for :mail do |f|
          %div.form-group
            %label Subject
            = f.text_field :subject, class: 'form-control', value: 'Welcome to the HiVE!'
          %div.form-group
            %label Content
            = f.text_area :content, class: 'form-control', rows: 13, value: "Hello #{user.name}, \n\nWelcome to the HiVE! I've got you all registered and invoiced, and you are officially a member of the HiVE! Your contract would have been sent to you via EchoSign for you to sign and return. Please let me know if it did not arrive. \n\nI have attached a little bit of information about how to be a great member of the HiVE and about our perks program. Also attached are instructions for connecting to the printer. Your user id for the printer is __ and the password is __. Printing is $0.10 per page for black and $0.35 for colour, billed every second month. \n\nPlease let me know if you have any questions or concerns! Thank you for joining the HiVE."
          %div.form-group
            %label
              = f.check_box :supplies, checked: false
              Include Supplies (gives a user a table of their current supplies).
              %br
            %label
              = f.check_box :account_type, checked: false
              Include Account Type (inserts a line into the message with the users account type).
              %br
            %label
              = f.check_box :sign_in_link, checked: true
              Include a Sign In Link (includes a link that allows users to log in and create a password).
          %div.form-group
            %label Attachments
            = f.select :attachments, options_from_collection_for_select(Attachment.all, :id, :filename), {},{multiple: true, class: 'form-control'}
          = submit_tag 'Send Email', class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
- cache set_keys([@user, @user.organization_members, Attachment, SupplyList], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Users'
    %div.col-md-10.shad-left
      %h1 Users
      %ul.nav.nav-tabs
        %li{ role: 'presentation' }
          = link_to 'Users', admin_users_path
        %li{ role: 'presentation' }
          = link_to 'New User', new_admin_user_path
        %li.active{ role: 'presentation' }
          = link_to @user.name, '#'

      %br
      %div.col-md-4
        - cache set_keys([@user]) do
          = render 'admin/users/form', url: admin_user_path(@user), method: :put, user: @user
      %div.col-md-8
        - cache set_keys([@user, @user.organization_members, Attachment, SupplyList]) do
          = render 'admin/users/list', user: @user

app/views/admin/users/index.html.haml
- cache set_keys([User], params) do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Users'
    %div.col-md-10.col-xs-12.shad-left
      %h1 Users

      %ul.nav.nav-tabs
        %li.active{ role: 'presentation' }
          = link_to 'Users', admin_users_path
        %li{ role: 'presentation' }
          = link_to 'New User', new_admin_user_path
      %br
      %div.search
        %div.col-md-4
          = render '/admin/shared/search_active'
        = render 'shared/pagination_top', object: @users

      = render 'admin/shared/table', model: User, data: @users, header: %w"Name Active Email Phone Account-Type Desk Actions",
        methods: [['Link', :name, :edit_admin_user_path], :active, :email, :phone, :account_type, :desk],
        links: [ ['edit', :edit_admin_user_path], ['delete', :admin_user_path, method: :delete, data: { confirm: 'This will delete the record in the database permanently.' }] ]

      %div.text-center
        = paginate @users, theme: 'twitter-bootstrap-3', pagination_class: 'pagination-centered'
        %br
        = page_entries_info @users
        %br
        %span Results:
        = link_to '10', params.merge(per_page: 10)
        = link_to '20', params.merge(per_page: 20)
        = link_to '50', params.merge(per_page: 50)
        = link_to '100', params.merge(per_page: 100)
        = link_to '200', params.merge(per_page: 200)

app/views/admin/users/new.html.haml
- cache do
  %div.container-fluid
    %div.col-md-2.sidebar.hidden-sm.hidden-xs
      = render 'admin/shared/sidebar', active: 'Users'
    %div.col-md-10.shad-left
      %h1 Users
      %ul.nav.nav-tabs
        %li{ role: 'presentation' }
          = link_to 'Users', admin_users_path
        %li.active{ role: 'presentation' }
          = link_to 'New User', new_admin_user_path

      %br
      %div.col-md-4
        = render 'admin/users/form', url: admin_users_path, method: :post, user: @user